"""DocGen Agent

Generates a professional, complete README.md for the auto-produced code,
including quality metrics from the pipeline run.
"""

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage


# ── Node ─────────────────────────────────────────────────────────────────────

def doc_gen_node(state: dict) -> dict:
    """LangGraph node: generate README.md from spec, code, and metrics."""
    llm = ChatOpenAI(model="gpt-4o", temperature=0.4)

    # Build code context for the prompt
    code_context = ""
    for filename, code in state.get("generated_code", {}).items():
        code_context += f"\n### `{filename}`\n```python\n{code}\n```\n"

    test_results  = state.get("test_results", {})
    lint_scores   = state.get("lint_scores", {})
    security_score = state.get("security_score", "N/A")
    fix_attempts  = state.get("fix_attempts", 0)
    elapsed       = state.get("elapsed_time", 0)

    avg_lint = (
        round(sum(lint_scores.values()) / len(lint_scores), 1)
        if lint_scores else "N/A"
    )

    prompt = f"""You are an expert technical writer. Write a complete, professional README.md.

ORIGINAL REQUIREMENT:
{state.get('requirement', '')}

TECHNICAL SPEC:
{state.get('technical_spec', '')}

GENERATED CODE:
{code_context}

QUALITY METRICS:
- Test Pass Rate : {test_results.get('pass_rate', 'N/A')}%
- Tests Passed   : {test_results.get('passed_count', 'N/A')} / {test_results.get('passed_count', 0) + test_results.get('failed_count', 0)}
- Avg Lint Score : {avg_lint}/10
- Security Score : {security_score}/10
- Self-Heal Loops: {fix_attempts}
- Time-to-Code   : {elapsed}s

README sections to include (in order):
1. Title + badge line: "🤖 Generated by Autonomous SDLC Assistant"
2. Short description (2–3 sentences)
3. ✨ Features (bullet list)
4. 🚀 Quick Start (installation + usage commands)
5. 📖 API Reference (every public function — signature, params, return, example)
6. 🧪 Testing (how to run pytest + expected output)
7. 📊 Quality Metrics (table with the metrics above)
8. 📝 Notes (any caveats, limitations)

Return ONLY the raw Markdown content. No extra explanation."""

    logs = list(state.get("logs", []))
    logs.append("📝 [DocGen] Generating README.md…")

    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        documentation = response.content.strip()
        logs.append("✅ [DocGen] README.md generated successfully")
        return {"documentation": documentation, "logs": logs}

    except Exception as exc:
        logs.append(f"❌ [DocGen] Error: {exc}")
        fallback = (
            f"# Generated Project\n\n"
            f"**Requirement**: {state.get('requirement', '')}\n\n"
            f"*Documentation generation failed: {exc}*"
        )
        return {"documentation": fallback, "logs": logs}
